"""empty message

Revision ID: 91d1a0e136a2
Revises: 90f92bcc1f9d
Create Date: 2024-07-13 23:01:31.151174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 추가


# revision identifiers, used by Alembic.
revision: str = '91d1a0e136a2'
down_revision: Union[str, None] = '90f92bcc1f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
